// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var essay = Essay.FromJson(jsonString);

namespace Dororin.Essay
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Essay
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }

        [JsonProperty("citation")]
        public string Citation { get; set; }

        [JsonProperty("furtherReading")]
        public string FurtherReading { get; set; }

        [JsonProperty("carouselObjectIds")]
        public string CarouselObjectIds { get; set; }

        [JsonProperty("authors")]
        public Authors Authors { get; set; }

        [JsonProperty("primaryEssays")]
        public PrimaryEssays PrimaryEssays { get; set; }

        [JsonProperty("secondaryEssay")]
        public SecondaryEssay SecondaryEssay { get; set; }

        [JsonProperty("pullquote")]
        public string Pullquote { get; set; }

        [JsonProperty("publishingInformation")]
        public string PublishingInformation { get; set; }

        [JsonProperty("importedId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ImportedId { get; set; }

        [JsonProperty("PostId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PostId { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("publishedDate")]
        public string PublishedDate { get; set; }
    }

    public partial class Authors
    {
        [JsonProperty("author")]
        public Author[] Author { get; set; }
    }

    public partial class Author
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("authorName")]
        public string AuthorName { get; set; }

        [JsonProperty("affiliation")]
        public string Affiliation { get; set; }
    }

    public partial class PrimaryEssays
    {
        [JsonProperty("primaryEssay")]
        public PrimaryEssay[] PrimaryEssay { get; set; }
    }

    public partial class PrimaryEssay
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }
    }

    public partial class SecondaryEssay
    {
        [JsonProperty("targetItems")]
        public PrimaryEssay[] TargetItems { get; set; }
    }

    public partial class Essay
    {
        public static Essay FromJson(string json) => JsonConvert.DeserializeObject<Essay>(json, Dororin.Essay.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Essay self) => JsonConvert.SerializeObject(self, Dororin.Essay.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
