// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dororin.SectionHeader;
//
//    var sectionHeader = SectionHeader.FromJson(jsonString);

namespace Dororin.SectionHeader
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SectionHeader
    {
        [JsonProperty("header")]
        public string Header { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("cta")]
        public string Cta { get; set; }
    }

    public partial class SectionHeader
    {
        public static SectionHeader FromJson(string json) => JsonConvert.DeserializeObject<SectionHeader>(json, Dororin.SectionHeader.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SectionHeader self) => JsonConvert.SerializeObject(self, Dororin.SectionHeader.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
