// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dororin.StreamsLandingPage;
//
//    var streamsLandingPage = StreamsLandingPage.FromJson(jsonString);

namespace Dororin.StreamsLandingPage
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StreamsLandingPage
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("metaTagKeywords")]
        public string MetaTagKeywords { get; set; }

        [JsonProperty("metaTagDescription")]
        public string MetaTagDescription { get; set; }

        [JsonProperty("children")]
        public StreamsLandingPageChild[] Children { get; set; }

        [JsonProperty("createdDate")]
        public string CreatedDate { get; set; }

        [JsonProperty("updatedDate")]
        public string UpdatedDate { get; set; }

        [JsonProperty("sortOrder")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long SortOrder { get; set; }
    }

    public partial class StreamsLandingPageChild
    {
        [JsonProperty("children")]
        public ChildChild[] Children { get; set; }
    }

    public partial class ChildChild
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("template")]
        public Template Template { get; set; }
    }

    public partial class Template
    {
        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class StreamsLandingPage
    {
        public static StreamsLandingPage FromJson(string json) => JsonConvert.DeserializeObject<StreamsLandingPage>(json, Dororin.StreamsLandingPage.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this StreamsLandingPage self) => JsonConvert.SerializeObject(self, Dororin.StreamsLandingPage.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
