// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dororin.YouTubeVideoPlayer;
//
//    var youTubeVideoPlayer = YouTubeVideoPlayer.FromJson(jsonString);

namespace Dororin.YouTubeVideoPlayer
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class YouTubeVideoPlayer
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("template")]
        public Template Template { get; set; }

        [JsonProperty("youTubeID")]
        public string YouTubeId { get; set; }
    }

    public partial class Template
    {
        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class YouTubeVideoPlayer
    {
        public static YouTubeVideoPlayer FromJson(string json) => JsonConvert.DeserializeObject<YouTubeVideoPlayer>(json, Dororin.YouTubeVideoPlayer.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this YouTubeVideoPlayer self) => JsonConvert.SerializeObject(self, Dororin.YouTubeVideoPlayer.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
